# Generated by Django 3.2.2 on 2021-05-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210514_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baby_age',
            field=models.CharField(choices=[('0', '0-6 months'), ('1', '6 months - 1 years'), ('2', '1-2 years'), ('3', '2-3 years'), ('4', '3-4 years'), ('5', '4-5 years'), ('6', '5-6 years')], default='0', max_length=20),
        ),
    ]
