# Generated by Django 3.2.2 on 2021-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_baby_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baby_age',
            field=models.CharField(choices=[('0', 'Upto 6 months'), ('1', 'Upto 1 years'), ('2', 'Upto 2 years'), ('3', 'Upto 3 years'), ('4', 'Upto 4 years'), ('5', 'Upto 5 years'), ('6', 'Upto 6 years')], default='0', max_length=20),
        ),
    ]
